apiVersion: v1
kind: Pod
metadata:
  name: backend-pod-1
  labels:
    app: backend-demo
spec:
  containers:
    - name: backend
      image: the-crucible_backend
      imagePullPolicy: IfNotPresent
      env:
        - name: PORT
          value: "4000"
      ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod-2
  labels:
    app: backend-demo
spec:
  containers:
    - name: backend
      image: the-crucible_backend
      imagePullPolicy: IfNotPresent
      env:
        - name: PORT
          value: "4000"
      ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod-3
  labels:
    app: backend-demo
spec:
  containers:
    - name: backend
      image: the-crucible_backend
      imagePullPolicy: IfNotPresent
      env:
        - name: PORT
          value: "4000"
      ports:
        - containerPort: 4000
