apiVersion: v1
kind: Service
metadata:
  name: backend-demo-svc
spec:
  type: NodePort
  selector:
    app: backend-demo
  ports:
    - name: http
      port: 4002
      targetPort: 4000
      nodePort: 30034
